
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[324] =
    {   0,
        0,    0,   93,   91,    2,    2,   84,   91,   77,   91,
       47,   48,   73,   75,   54,   76,   55,   74,   87,   53,
       78,   56,   79,   89,   51,   52,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   49,   91,   50,   83,
        0,   90,   85,   59,   57,   60,   58,   88,    1,   88,
       87,   80,   82,   81,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   36,   89,
       89,   89,   89,   89,   16,   89,   89,   89,   89,   89,
       89,   89,   89,   14,   89,   89,   89,   89,   89,   89,

       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   86,    1,   88,   68,   89,   89,   89,   89,   89,
       89,   62,   89,   89,   89,   89,   89,   89,   89,   89,
       17,   89,   89,    3,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   61,   89,   89,   89,
       89,   63,   89,   89,   89,   89,   89,   89,   89,   89,
       65,   37,   89,   64,   66,   89,   39,   89,   89,   18,
       19,   89,   40,   89,   89,   41,   89,   42,   43,   89,
       44,   89,   89,   72,   89,   89,   89,   89,   89,   38,
       89,   67,   89,   89,   89,   89,   89,   21,   89,   45,

       46,   89,   89,   89,   89,   22,   69,   89,   89,   89,
       89,   89,   89,   89,   20,   89,   89,   89,   23,   89,
       89,   89,   89,   89,   89,   89,    8,    4,   89,   89,
       89,   89,   89,   89,   89,    7,   70,   89,   89,   89,
        5,   89,   89,   89,   89,   89,   89,   89,   11,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   10,
       71,   89,   26,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,    6,   15,   27,   89,   24,
       89,   89,   89,   89,    9,   89,   89,   89,   89,   89,
       89,   35,   34,   25,   89,   89,   89,   89,   89,   89,

       89,   13,   89,   89,   31,   89,   89,   89,   89,   89,
       89,   89,   89,   33,   12,   28,   89,   32,   89,   89,
       30,   29,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       24,    1,   25,    1,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    1,    1,
        1,    1,    4,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[328] =
    {   0,
        0,    0,  129,  995,  995,  995,  106,  115,  995,   98,
      995,  995,  995,   44,  995,   43,   41,   85,   45,  995,
       78,   69,   66,   49,  995,  995,   51,   54,   57,   64,
       66,   68,   60,   91,   93,   95,   98,  100,  102,  105,
      117,  119,  128,  133,  140,  146,  995,   22,  995,  995,
       67,  995,  995,  995,  995,  995,  995,  107,    0,  149,
      153,  995,  995,  995,    0,  156,  161,  163,  167,  170,
      172,  174,  176,  178,  182,  185,  191,  193,    0,  197,
      199,  201,  204,  207,  209,  222,  227,  229,  232,  234,
      236,  238,  244,  252,  255,  257,  259,  261,  263,  266,

      269,  271,  276,  284,  286,  290,  292,  294,  296,  299,
      301,  995,    0,  304,  307,  318,  320,  325,  327,  329,
      331,  333,  335,  337,  339,  341,  344,  356,  358,  363,
      365,  360,  367,  370,  374,  376,  378,  380,  382,  385,
      388,  390,  398,  403,  400,  405,  417,  419,  423,  425,
      427,  430,  433,  436,  438,  441,  443,  446,  448,  458,
      460,  462,  466,  468,  470,  474,  477,  479,  483,  485,
      487,  489,  496,  498,  501,  504,  506,  508,  512,  516,
      514,  518,  520,  522,  527,  529,  531,  535,  540,  542,
      546,  548,  550,  552,  556,  561,  563,  565,  571,  574,

      576,  579,  581,  583,  587,  589,  591,  593,  599,  601,
      603,  605,  612,  610,  615,  617,  622,  624,  629,  631,
      636,  640,  642,  649,  651,  653,  657,  660,  662,  666,
      669,  672,  676,  680,  682,  684,  686,  691,  693,  697,
      700,  708,  710,  712,  714,  716,  722,  725,  727,  729,
      731,  733,  736,  738,  744,  741,  750,  752,  756,  758,
      763,  766,  769,  771,  773,  775,  783,  778,  786,  788,
      790,  795,  799,  801,  806,  803,  811,  813,  817,  819,
      825,  830,  832,  835,  837,  839,  841,  843,  845,  850,
      852,  856,  859,  861,  864,  868,  875,  877,  881,  883,

      885,  887,  889,  894,  896,  899,  903,  907,  910,  916,
      918,  920,  922,  924,  930,  934,  936,  940,  943,  946,
      948,  950,  995,  986,   66,  990,   57
    } ;

static const flex_int16_t yy_def[328] =
    {   0,
      323,    1,  323,  323,  323,  323,  323,  324,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  325,  323,  323,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  323,  323,  323,  323,
      324,  323,  323,  323,  323,  323,  323,  323,  326,  323,
      323,  323,  323,  323,  327,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  327,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  323,  326,  323,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,    0,  323,  323,  323,  323
    } ;

static const flex_int16_t yy_nxt[1051] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   19,   20,   21,
       22,   23,   24,   25,   26,   24,   27,   24,   28,   29,
       30,   31,   24,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   24,   41,   42,   43,   44,   24,   45,   24,
       24,   46,   47,   48,   49,   54,   56,   58,   58,   60,
       65,   61,   61,   57,   55,   65,   65,   65,   65,   66,
       65,   65,   52,   65,   65,  112,   65,   65,   67,   68,
       65,   65,   65,   79,   65,   65,   64,   69,   73,   63,
       70,   85,   80,   75,   74,   71,   72,   76,   62,   86,

       59,   77,   81,   82,   84,   53,   83,   65,   65,   65,
       65,   65,   65,   78,   65,   65,   65,   65,   65,   65,
       52,   65,   65,   58,   58,   89,   50,   87,  323,   88,
       93,   90,   91,   65,   65,   65,   65,  323,   92,   95,
      323,   94,  323,   97,   65,   65,  323,   98,   96,   65,
       65,   99,  323,  100,  105,  101,   65,   65,  106,  323,
      102,  103,   65,   65,  104,  114,  114,   60,  107,   61,
       61,  108,   65,   65,  109,  323,  110,   65,   65,   65,
       65,  323,  111,   65,   65,  323,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,  323,  117,   65,   65,

      120,   65,   65,  116,  118,  115,  119,   65,   65,   65,
       65,  323,  123,   65,   65,   65,   65,   65,   65,  121,
       65,   65,  122,   65,   65,   65,   65,  127,  323,  129,
      323,  124,  323,  125,  128,  126,  323,  132,   65,   65,
      323,  130,  323,   65,   65,   65,   65,  131,   65,   65,
       65,   65,   65,   65,   65,   65,  133,  135,  323,  136,
       65,   65,  323,  137,  138,  139,  323,  134,   65,   65,
      141,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,  323,   65,   65,  140,   65,   65,   65,   65,  145,
      323,  143,   65,   65,  323,  146,  323,  149,  144,  148,

       65,   65,   65,   65,  142,  147,   65,   65,   65,   65,
       65,   65,   65,   65,  323,   65,   65,   65,   65,  150,
      114,  114,  158,   65,   65,  152,  323,  151,  156,  159,
      323,  160,  323,  153,   65,   65,   65,   65,  155,  154,
      157,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,  166,
       65,   65,  161,  163,  168,  323,  164,  323,  165,  323,
      162,  170,   65,   65,   65,   65,   65,   65,  169,   65,
       65,   65,   65,   65,   65,  167,   65,   65,  323,  171,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,

      172,   65,   65,  174,   65,   65,   65,   65,  173,  323,
      176,  182,  177,  175,   65,   65,   65,   65,  323,   65,
       65,   65,   65,  180,  178,  323,  179,  323,  185,  183,
      181,  184,  187,   65,   65,   65,   65,  186,  189,   65,
       65,   65,   65,   65,   65,  188,   65,   65,  323,   65,
       65,  191,   65,   65,   65,   65,  323,   65,   65,   65,
       65,  193,   65,   65,   65,   65,  196,  197,  323,  190,
      192,  194,  323,  198,   65,   65,   65,   65,   65,   65,
      323,  195,   65,   65,   65,   65,   65,   65,  323,  199,
       65,   65,  202,   65,   65,   65,   65,  323,  200,   65,

       65,   65,   65,   65,   65,   65,   65,  323,  201,  205,
      323,  203,   65,   65,   65,   65,  204,   65,   65,  206,
       65,   65,   65,   65,   65,   65,  323,  208,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
      209,  207,  210,   65,   65,   65,   65,   65,   65,  323,
      213,   65,   65,  214,  211,  212,   65,   65,   65,   65,
      323,  217,   65,   65,   65,   65,   65,   65,   65,   65,
      323,  216,   65,   65,  215,  323,  219,   65,   65,   65,
       65,   65,   65,  222,  323,  218,  221,   65,   65,  220,
       65,   65,   65,   65,  223,   65,   65,   65,   65,   65,

       65,  323,  224,   65,   65,   65,   65,   65,   65,   65,
       65,  227,  323,  228,  225,   65,   65,   65,   65,   65,
       65,   65,   65,  323,  226,  231,   65,   65,   65,   65,
      229,   65,   65,   65,   65,  234,  230,  235,   65,   65,
       65,   65,  323,  233,  232,   65,   65,   65,   65,  323,
      239,  236,   65,   65,  323,  237,   65,   65,   65,   65,
      323,  238,  240,  241,  323,   65,   65,   65,   65,   65,
       65,  323,  244,   65,   65,  242,   65,   65,   65,   65,
      243,  245,   65,   65,  323,   65,   65,  247,   65,   65,
      323,  246,   65,   65,  323,  249,   65,   65,   65,   65,

       65,   65,   65,   65,  323,  248,  250,   65,   65,   65,
       65,  254,  323,   65,   65,  251,   65,   65,  253,  323,
      255,  323,  252,  256,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,  259,  323,  257,  258,   65,   65,
      323,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,  262,   65,   65,   65,   65,  261,   65,   65,  260,
       65,   65,  264,  266,  263,  265,   65,   65,   65,   65,
      323,  267,   65,   65,   65,   65,  269,  268,  272,   65,
       65,  270,   65,   65,  271,   65,   65,   65,   65,   65,
       65,   65,   65,  273,   65,   65,  276,  323,  274,   65,

       65,  275,   65,   65,   65,   65,   65,   65,  281,  323,
      277,   65,   65,  323,  283,   65,   65,   65,   65,   65,
       65,  278,   65,   65,  323,  285,  279,   65,   65,   65,
       65,  280,  282,   65,   65,   65,   65,  284,  323,  286,
      288,   65,   65,  289,  323,  287,   65,   65,   65,   65,
      290,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,  323,  292,  293,   65,   65,   65,   65,
      323,  295,   65,   65,  291,   65,   65,   65,   65,  298,
       65,   65,  300,  296,   65,   65,  323,  294,  323,  301,
      297,   65,   65,   65,   65,  323,  299,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,  302,  306,  303,
       65,   65,   65,   65,  307,   65,   65,  304,  323,   65,
       65,  323,  305,   65,   65,  323,   65,   65,  311,  309,
      323,  308,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,  310,  313,  323,  312,   65,   65,  314,  315,
       65,   65,   65,   65,  323,  316,   65,   65,  317,   65,
       65,  318,   65,   65,   65,   65,   65,   65,  323,  323,
      319,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  321,  323,  320,  322,   51,  323,  323,   51,
      113,  323,  113,  113,    3,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323
    } ;

static const flex_int16_t yy_chk[1051] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   14,   16,   17,   17,   19,
      327,   19,   19,   16,   14,   24,   24,   27,   27,  325,
       28,   28,   51,   29,   29,   48,   33,   33,   27,   27,
       30,   30,   31,   31,   32,   32,   23,   27,   28,   22,
       27,   33,   31,   29,   28,   27,   27,   29,   21,   33,

       18,   30,   31,   31,   32,   10,   31,   34,   34,   35,
       35,   36,   36,   30,   37,   37,   38,   38,   39,   39,
        8,   40,   40,   58,   58,   36,    7,   34,    3,   35,
       38,   36,   37,   41,   41,   42,   42,    0,   37,   40,
        0,   39,    0,   41,   43,   43,    0,   41,   40,   44,
       44,   41,    0,   42,   43,   42,   45,   45,   43,    0,
       42,   42,   46,   46,   42,   60,   60,   61,   43,   61,
       61,   43,   66,   66,   44,    0,   45,   67,   67,   68,
       68,    0,   46,   69,   69,    0,   70,   70,   71,   71,
       72,   72,   73,   73,   74,   74,    0,   69,   75,   75,

       72,   76,   76,   68,   70,   67,   71,   77,   77,   78,
       78,    0,   75,   80,   80,   81,   81,   82,   82,   73,
       83,   83,   74,   84,   84,   85,   85,   78,    0,   81,
        0,   76,    0,   76,   80,   77,    0,   84,   86,   86,
        0,   82,    0,   87,   87,   88,   88,   83,   89,   89,
       90,   90,   91,   91,   92,   92,   86,   87,    0,   88,
       93,   93,    0,   89,   90,   91,    0,   86,   94,   94,
       93,   95,   95,   96,   96,   97,   97,   98,   98,   99,
       99,    0,  100,  100,   92,  101,  101,  102,  102,   98,
        0,   96,  103,  103,    0,   99,    0,  102,   97,  101,

      104,  104,  105,  105,   95,  100,  106,  106,  107,  107,
      108,  108,  109,  109,    0,  110,  110,  111,  111,  103,
      114,  114,  109,  115,  115,  105,    0,  104,  108,  110,
        0,  111,    0,  106,  116,  116,  117,  117,  107,  106,
      108,  118,  118,  119,  119,  120,  120,  121,  121,  122,
      122,  123,  123,  124,  124,  125,  125,  126,  126,  121,
      127,  127,  116,  118,  124,    0,  119,    0,  120,    0,
      117,  126,  128,  128,  129,  129,  132,  132,  125,  130,
      130,  131,  131,  133,  133,  123,  134,  134,    0,  127,
      135,  135,  136,  136,  137,  137,  138,  138,  139,  139,

      128,  140,  140,  130,  141,  141,  142,  142,  129,    0,
      132,  139,  133,  131,  143,  143,  145,  145,    0,  144,
      144,  146,  146,  137,  135,    0,  136,    0,  142,  140,
      138,  141,  144,  147,  147,  148,  148,  143,  146,  149,
      149,  150,  150,  151,  151,  145,  152,  152,    0,  153,
      153,  149,  154,  154,  155,  155,    0,  156,  156,  157,
      157,  151,  158,  158,  159,  159,  155,  156,    0,  148,
      150,  153,    0,  157,  160,  160,  161,  161,  162,  162,
        0,  154,  163,  163,  164,  164,  165,  165,    0,  158,
      166,  166,  163,  167,  167,  168,  168,    0,  159,  169,

      169,  170,  170,  171,  171,  172,  172,    0,  160,  169,
        0,  166,  173,  173,  174,  174,  168,  175,  175,  172,
      176,  176,  177,  177,  178,  178,    0,  175,  179,  179,
      181,  181,  180,  180,  182,  182,  183,  183,  184,  184,
      177,  174,  180,  185,  185,  186,  186,  187,  187,    0,
      183,  188,  188,  185,  180,  182,  189,  189,  190,  190,
        0,  188,  191,  191,  192,  192,  193,  193,  194,  194,
        0,  187,  195,  195,  186,    0,  191,  196,  196,  197,
      197,  198,  198,  195,    0,  189,  194,  199,  199,  193,
      200,  200,  201,  201,  196,  202,  202,  203,  203,  204,

      204,    0,  197,  205,  205,  206,  206,  207,  207,  208,
      208,  203,    0,  204,  199,  209,  209,  210,  210,  211,
      211,  212,  212,    0,  202,  209,  214,  214,  213,  213,
      205,  215,  215,  216,  216,  212,  208,  213,  217,  217,
      218,  218,    0,  211,  210,  219,  219,  220,  220,    0,
      218,  214,  221,  221,    0,  216,  222,  222,  223,  223,
        0,  217,  218,  220,    0,  224,  224,  225,  225,  226,
      226,    0,  223,  227,  227,  221,  228,  228,  229,  229,
      222,  224,  230,  230,    0,  231,  231,  226,  232,  232,
        0,  225,  233,  233,    0,  230,  234,  234,  235,  235,

      236,  236,  237,  237,    0,  229,  231,  238,  238,  239,
      239,  235,    0,  240,  240,  232,  241,  241,  234,    0,
      235,    0,  233,  238,  242,  242,  243,  243,  244,  244,
      245,  245,  246,  246,  242,    0,  239,  240,  247,  247,
        0,  248,  248,  249,  249,  250,  250,  251,  251,  252,
      252,  245,  253,  253,  254,  254,  244,  256,  256,  243,
      255,  255,  247,  250,  246,  248,  257,  257,  258,  258,
        0,  251,  259,  259,  260,  260,  253,  252,  256,  261,
      261,  254,  262,  262,  255,  263,  263,  264,  264,  265,
      265,  266,  266,  257,  268,  268,  262,    0,  258,  267,

      267,  259,  269,  269,  270,  270,  271,  271,  268,    0,
      264,  272,  272,    0,  270,  273,  273,  274,  274,  276,
      276,  265,  275,  275,    0,  272,  266,  277,  277,  278,
      278,  267,  269,  279,  279,  280,  280,  271,    0,  273,
      275,  281,  281,  279,    0,  274,  282,  282,  283,  283,
      281,  284,  284,  285,  285,  286,  286,  287,  287,  288,
      288,  289,  289,    0,  283,  284,  290,  290,  291,  291,
        0,  287,  292,  292,  282,  293,  293,  294,  294,  290,
      295,  295,  291,  288,  296,  296,    0,  286,    0,  295,
      289,  297,  297,  298,  298,    0,  290,  299,  299,  300,

      300,  301,  301,  302,  302,  303,  303,  296,  300,  297,
      304,  304,  305,  305,  301,  306,  306,  298,    0,  307,
      307,    0,  299,  308,  308,    0,  309,  309,  306,  303,
        0,  301,  310,  310,  311,  311,  312,  312,  313,  313,
      314,  314,  304,  307,    0,  306,  315,  315,  308,  309,
      316,  316,  317,  317,    0,  310,  318,  318,  311,  319,
      319,  312,  320,  320,  321,  321,  322,  322,    0,    0,
      313,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  319,    0,  317,  320,  324,    0,    0,  324,
      326,    0,  326,  326,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gpl.l"
#line 2 "gpl.l"

#include "error.h"
#include "parser.h" // replacement for y.tab.h

#include <ctype.h>
#include <iostream>
using namespace std;


int line_count = 1;          // used to keep track of the input line

extern Error error_handler;  // error reporting object

/* count line feeds */
void count_lines(char *str)
{
  while(*str)
  {
    if (*str++ == '\n')
    {
        line_count ++;
    }
  }
}

void discard()
{
  count_lines(yytext);
}

/* the following functions are "called" when a token is found */

int emit(int token)
{
  return(token);
}

int emit_with_line_number(int token)
{
  yylval.union_int = line_count;
  return emit(token);
}

int emit_error(int token)
{
  error_handler.error(Error::ILLEGAL_TOKEN,yytext);
  yylval.union_string = new string(yytext);
  return emit(token);
}

int j;



void get_int_value()
{
  // assumes that the string in yytext is an integer
  // convert the string yytext into an integer
  // put the int into global union used to send values to the parser (record.y)
  // the union and its union_int field are declared in record.y
  yylval.union_int = atoi(yytext);
}

void get_double_value()
{
  yylval.union_double = atof(yytext);
}

void get_string_value()
{
  // Would like to put a string in the union, but the way the union works
  // it has to be a pointer to a string.
  yylval.union_string = new string(yytext);
}
 



#line 857 "lex.yy.c"
#line 858 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 82 "gpl.l"


#line 1078 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 324 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 995 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "gpl.l"
discard();
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 85 "gpl.l"
discard();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 87 "gpl.l"
return emit(T_INT);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "gpl.l"
return emit(T_DOUBLE);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "gpl.l"
return emit(T_STRING);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "gpl.l"
return emit(T_TRIANGLE);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "gpl.l"
return emit(T_PIXMAP);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "gpl.l"
return emit(T_CIRCLE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "gpl.l"
return emit(T_RECTANGLE);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "gpl.l"
return emit(T_TEXTBOX);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "gpl.l"
return emit(T_FORWARD);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "gpl.l"
return emit(T_INITIALIZATION);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "gpl.l"
return emit(T_TERMINATION);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "gpl.l"
return emit(T_ON);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "gpl.l"
return emit(T_ANIMATION);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "gpl.l"
return emit(T_IF);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "gpl.l"
return emit(T_FOR);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "gpl.l"
return emit(T_ELSE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "gpl.l"
return emit_with_line_number(T_EXIT);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "gpl.l"
return emit_with_line_number(T_PRINT);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 106 "gpl.l"
return emit(T_TRUE);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "gpl.l"
return emit(T_FALSE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "gpl.l"
return emit(T_SPACE);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "gpl.l"
return emit(T_LEFTARROW);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "gpl.l"
return emit(T_RIGHTARROW);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "gpl.l"
return emit(T_UPARROW);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "gpl.l"
return emit(T_DOWNARROW);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 114 "gpl.l"
return emit(T_LEFTMOUSE_DOWN);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 115 "gpl.l"
return emit(T_MIDDLEMOUSE_DOWN);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "gpl.l"
return emit(T_RIGHTMOUSE_DOWN);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "gpl.l"
return emit(T_LEFTMOUSE_UP);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "gpl.l"
return emit(T_MIDDLEMOUSE_UP);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 119 "gpl.l"
return emit(T_RIGHTMOUSE_UP);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "gpl.l"
return emit(T_MOUSE_MOVE);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "gpl.l"
return emit(T_MOUSE_DRAG);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "gpl.l"
return emit(T_F1);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "gpl.l"
return emit(T_AKEY);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 "gpl.l"
return emit(T_SKEY);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "gpl.l"
return emit(T_DKEY);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "gpl.l"
return emit(T_FKEY);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "gpl.l"
return emit(T_HKEY);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 "gpl.l"
return emit(T_JKEY);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 129 "gpl.l"
return emit(T_KKEY);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 "gpl.l"
return emit(T_LKEY);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 "gpl.l"
return emit(T_WKEY);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 132 "gpl.l"
return emit(T_ZKEY);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 134 "gpl.l"
return emit(T_LPAREN);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 135 "gpl.l"
return emit(T_RPAREN);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 136 "gpl.l"
return emit(T_LBRACE);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 137 "gpl.l"
return emit(T_RBRACE);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 138 "gpl.l"
return emit(T_LBRACKET);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 139 "gpl.l"
return emit(T_RBRACKET);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 140 "gpl.l"
return emit(T_SEMIC);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 141 "gpl.l"
return emit(T_COMMA);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 142 "gpl.l"
return emit(T_PERIOD);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "gpl.l"
return emit(T_ASSIGN);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 145 "gpl.l"
return emit(T_PLUS_ASSIGN);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 146 "gpl.l"
return emit(T_MINUS_ASSIGN);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 147 "gpl.l"
return emit(T_PLUS_PLUS);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 148 "gpl.l"
return emit(T_MINUS_MINUS);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 150 "gpl.l"
return emit(T_SIN);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 151 "gpl.l"
return emit(T_COS);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 152 "gpl.l"
return emit(T_TAN);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 153 "gpl.l"
return emit(T_ASIN);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 154 "gpl.l"
return emit(T_ACOS);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 155 "gpl.l"
return emit(T_ATAN);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 156 "gpl.l"
return emit(T_SQRT);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 157 "gpl.l"
return emit(T_ABS);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 158 "gpl.l"
return emit(T_FLOOR);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 159 "gpl.l"
return emit(T_RANDOM);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 161 "gpl.l"
return emit(T_TOUCHES);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 162 "gpl.l"
return emit(T_NEAR);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 164 "gpl.l"
return emit(T_MULTIPLY);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 165 "gpl.l"
return emit(T_DIVIDE);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 166 "gpl.l"
return emit(T_PLUS);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 167 "gpl.l"
return emit(T_MINUS);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 168 "gpl.l"
return emit(T_MOD);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 170 "gpl.l"
return emit(T_LESS);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 171 "gpl.l"
return emit(T_GREATER);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 172 "gpl.l"
return emit(T_LESS_EQUAL);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 173 "gpl.l"
return emit(T_GREATER_EQUAL);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 174 "gpl.l"
return emit(T_EQUAL);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 175 "gpl.l"
return emit(T_NOT_EQUAL);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 176 "gpl.l"
return emit(T_NOT);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 177 "gpl.l"
return emit(T_AND);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 178 "gpl.l"
return emit(T_OR);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 180 "gpl.l"
get_int_value(); return T_INT_CONSTANT;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 181 "gpl.l"
get_double_value(); return T_DOUBLE_CONSTANT;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 182 "gpl.l"
get_string_value(); return T_ID;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 183 "gpl.l"
yylval.union_string = new string(yytext, 1, yyleng - 2); return T_STRING_CONSTANT;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 185 "gpl.l"
return emit_error(T_ERROR);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 186 "gpl.l"
ECHO;
	YY_BREAK
#line 1596 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 324 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 324 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 323);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 186 "gpl.l"
